package de.stullrich.securenotes.util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseUtil {

	private static final Logger logger = LoggerFactory.getLogger(DatabaseUtil.class);
	private static final String CLEARTEXT1 = "Personal data should no longer be able to be attributed to a specific data subject without additional information, provided that this additional information is kept separately and is subject to technical and organisational measures which ensure that the personal data is not attributed to an identified or identifiable natural person. The measures shall take into account the state of the art, the implementation costs as well as the type, scope, circumstances and purpose of the processing. In addition to these criteria, the different probabilities of occurrence and the severity of the risk to the rights and freedoms of the data subjects must also be taken into account. Accordingly, the level of security measures taken should be adapted. Encryption is explicitly mentioned as such a measure in the non-exhaustive catalogue of Art. 32. You must report a data breach if it poses a risk to the data subject. According to Art. 4 No. 12 GDPR, a violation of personal data exists if personal data have been lost or have been destroyed, altered or disclosed without authorisation. The supervisory authorities shall ensure that the fines provided for in the article for infringements of the GDPR are effective, proportionate and dissuasive in each individual case.";
	private static final String CLEARTEXT2 = "Encryption is a form of pseudonymisation. The key stands for the additional information. If the key is kept together with the data, encrypted data can be made publicly accessible, e.g. in the event of a phishing attack. Pseudonymisation is then no longer possible. In order to ensure adequate protection, personal data should be encrypted. However, not all types of encryption provide the same level of protection. For maximum security, encryption keys should be controlled by the user. No one else should have access to them during the encryption and decryption process. In the event of a data protection breach, the responsible person must report the breach to the competent supervisory authority without delay and, if possible, within 72 hours of becoming aware of the breach. Unless the breach is unlikely to create a risk to the protection of personal data. Fines are imposed according to the circumstances of the individual case. In deciding on the imposition and the amount thereof, account shall be taken in each individual case of the measures taken.";
	private static final String CLEARTEXT3 = "With client-side encryption there is no possibility to decrypt the files on the server, e.g. in case of a phishing attack, because only encrypted key material is stored there. The key that encodes the data never leaves the user''s computer in plain text. If client-side encryption is used, it is impossible to decrypt the files in case of an attack on the server, because the key is held by the owner. Therefore, hacks on servers are not considered as data mishaps and the notification rules of the GDPR do not apply. This means that you save the cost of data failure notifications and possible fines, maintain your reputation and protect the privacy of your employees and customers. Since all files are encrypted on the user''s end device, only unreadable data can be known. These are not considered personal data or data mishaps. Fines are therefore avoided.";
	private static final String TITLE1 = "What GDPR says";
	private static final String TITLE2 = "What that means";
	private static final String TITLE3 = "How client-side encryption helps";
	private static final String NOTE1 = "U2FsdGVkX1+qPXJKqCyHzjr+Y6sU1Zdd/GP9QJ+l4C9eup4L3au/roQTxV8WQxfgC6cde9qw4NGMV3+1tcNC2FotPpbNJGSoIhz/RUEY8DA/ZFD4f2wh7kqLSqARJme44BhMl7/8ZJVSrgbjE6MLILtNdMPxHDHr8izRf1VG5ihceLwf/letxkJmAlZYaWfNQq0J2VDM0Fp7kpbEs23r4KyB7HJd6IdAMG36+3/u1gQuHyA9+wjxlh1mIyur4A556RKpaM70Zr8zpjOvjiBdK9ONkDrX8qxSzS2nJJk0aTgRmMR29auY4uNEH6O1jPD2xWyNiyA7zb9Hn/tma9R/wG4KljqlpQZ4r8lyISLANZEtsdxvcZ9DA6IKq/zuZ1iNInAXxTSIjmJvMTC4WJr2E7RqWfSPs0pTTx/FHt5AmafEcjyRCX1o2MrOKTlli+BGO1lNWOWKR9KIKF3B3Y468f8RiVzD2GMLp0nXSYNl0qouYwpxIT/Z6L+f4PC0vsPLoUkGMID4dAn+CQXo64aVcpf6chNUvWOHGI9aM0sgiAgF9atCmbcgwhUZFH3wtUcPrfmmbALMkGH/V2tNXjLBx67DQbPpgeUfVmKw57jPqJnmDh9vUIt87UF0jN+gKBv2Jw50NiTMRppX+gVDBzTp79Hxy9SFCdr1zYF5oliH84oMguJ/nisyaY1wZlJIo/cnbMekke//EQlmTOfOLaFSYglR3UL0fj869sZYbJmbOSozgR9SEnAxuFOyt4lLiPcQUEujpszhEPB8EAkBdywnoG1CmM8P9WZJ7ORP9aMVcPLd2H/c9V46B4pHb5LuxEX0AsHP8j6/OSXBI4PFIHKhN9ZF51UqRT3E2BQl7TEr4DgFGQXJhlhrNToK5xPZ9upJIM3BYx0jN8TuA98woHY1bifeIthO4U1mO2mnnPLEPDZiZB2Gj8td6AV2gmxscw3zeai7dI7ChRBdkkzbn6KY64/qvclcLDilDB23RtB8BslK16tLfkNfCCrr5fpaDkKrHYsFeDqpmztGnkFa1++npJTZvfCBg7RSUUk/LWgGfuHUNxoOcwNZPZrwy6Jtp2Y8xtzHtQL6uUOlkMm23589vFTeIHdVc6T2dyiIyBul9ZwK63lEKEFcuKZdObkumb/AZAlJ8Mssf7fYIEsHFouThbWJ8heerZWacU1IRXnlsxfybS7zqzPAvV6MlczIu80l4knn42Cg1tY1GmwyEnG65ug5R+/DcDse14gFLges19MO+UhfJ+uJ66l/B7aqCa/DrUk/1T39n5c5IzWYGkWaW0t+KZEbX2QeDgEIw+44MuDxAXcvAyPKqlvT+jgbsC8EElDlEcwnb1vJGwenYp3Z3skW+cK8Nu1K2i7TF/dQiHWvF0HDXwUAfBBw9069fSwjy3jnO9H1Y1sQlOi7t7d5i4F1370D0w0RUo8WlGCmmFRmi3CG24dCMGBpTg2uEcqEExJwxRpcDlCYGNbBWdun6o1WljydoRuQ7gu1iQppz/Dri4vEB+N0LWlrTswwKbH1sYeLgyvym8DBO5IwoUQfxnC3ksBYmmMx9mr1ZBluaHHmnOVHH5N8GcFWkhFidLKRlzx7tlwMEmyHeMVrxVmNglj6GIMAGp43+GR1lZZ502EbM+BbtjaPlcemH6/pfViMDy5Qp4+wjxKh7x4TGh2/J8nU5D2gKmaGjk/JAzcBfzM=";
	private static final String NOTE2 = "U2FsdGVkX196EMV0DUfWRciynkB5ws3mmfqSJ145NGc5Q0rVxxGsXJgvIIb9dBugl8qwAcPPuBQkE517Xk0wW/DU9dIK3/EiFyYzv9QpspXvYnhkBTXW+NuDqTn7P03ePUHtAgbB5ZT4mNLzbB1SXl+m+NSokDx2Xo957Uert6VhbX3FwiBhOu/r+zn4/VoFRJKmXIR7VqEIuDAS9XqfHGMs0LEMm50WyDGUKmhWwbAbt5S7eL92/M0JNeAERAbxByPHjWwu2ytGKxX2mEkdX28PU+rM+nz70e5acj3kQ/rfc/ndhMZZH5FeQkutFVBK22s8nZv8VOAFvRbG29IyJlND1hdnwcd4MeeOh87VVbjHg/AUg0AUFk1Y3CRIJiWJMLW/NxGAOa+KE2NWdoI3ImoYsWIhzrPL2tmEAVJ2F49zHK3gSoYWDl8GYT+GCp3OZPsXZf0omMQo0A4V1v1eBAHaDN3yY/GyRBvXAQQ25Ka+5RB2rX5xkRh8A5t0zqSInhrEVTyT2nHPJ11L6ovIA+0JcNuOg1UyQGwsZqw/u1O0+9xjjmcxHIEaHx+NTUQY3+3LPedHwHOpvMbjLIiFiVUjQ46FOoks5Djf1vUZt+r0QbEQBHcGMG0k08TE3KpOSwbhYeYOp+DO1y/TaEiD0OfcZrk0VfdP50Qtqj//3WXWXzanbjuDPToRMqPqFC2D1RhhrM79qBimAx4Knt2167vsGMKYWY7HyeiGLg8D21BzIu768RQHM15+P+XkQauYKUV3wR8HBgXSgOjsLp9BRhFYUYA1EzCZ+It7FtKtc/LmTNueoPsJHEkTYIK7A1Lh2NdBceT9h6koAM0eUuH6RHDtv2UuAQNug6Lu8tUqEMJGICg6e/WHO9o9vcZq6LoRll39H+nWNy5XrXCZMqTFEzvHpNtlMnHEJVGXJ+vx/OZ4qEl8zKkNOMZAdkI4mKKRLXO5ZZmg7/vVImHbnNfRDqarUTWbvnB5MW2+tN92bqetPWNNh8y1eUNBYC4tGcHDgr4sE+LTDi6GXvrDX28C4CibmI85qyPacYE1f5TA/H9cP7E82VEz/5f23dFwJe9eXl9NHvm5aAJEkFGC3tF8zlayUsuBRuU07V8rEjENT/LHHiduA/ySGcXo64UTXh3YMo+RYgN++1untENbZKn6SL1gyGGGfofKh+XlaxuNInUDYLlF/GJ7y6108pFR+6ZXbi/bmzjMH7tIUjSl0tdcDO9C7DZMymrFYuEXgoFap4N0DV1sC7kpgqD9NIAjwk2GqaiUq0C3FfEmp6wUB8rrxSfYueTuzHzGPdPwEj1Efw03mdQQKYcbEprCRyQeYk+Pn4by7Ne+F2xGVLGubZAObet9J1OlwIiHw/0T/FZOMCvDiV2if+uVaEVruj7cejfltlU4sK3VT9fZ1rp3FOfqfNG6FdD4OW6VS99d0PwnswE=";
	private static final String NOTE3 = "U2FsdGVkX18JuhuAOEG6BzvyBYxmceJ+NEC+pjD6khUdvuIPkIgYPl1dSx9ihbaiQr/Byh6cyD0KZsvY/M3vISG+if4B8jJ7XvG5bkTjGyCG+Vr2fFwohZr1ARQfqEYC+a0CytcfV5Me+6GMW6hrApSKwF3UuxFBgMOxzeHagrhzvYz83j/5a/w/7kkvZSBmseNfw2UppWGwY/Uytn6TTsq9YNHNbw9sExvZ8I0xJ8zY9z0itF6D1KsurwVeKdB3+KOISCSrvGuUtbAEoM2e5ResRuCVtDcN0Wap1Ypsh+vNnOiaMadWC7wxP0AV4w8NFKQtxlpBHDhk+xsq4GrKnbfZDCVg+77/zCXvzC+tkNI9haNuu3eSDQCbyKeLCFIR+HbDXjs78+iIZOjS0BBWEA+xzk9W20m/tYgJRYJf7xbj3mHoN7e/zlrA977/unvbwdRZKRx+XCB9hIeXHiRUqqbx8dQLZ/h65J/UuC+8sV5dsHVBo3204iwJ7xqLxk6EV4zYQ1G/wp5wYQIToGOplf/5JSo0RwRNtw+n7a/ugh2D6+8YcFbDA1uD0xMjC1JLD8qOJL7XjT6aC6TugN/oaCm8XHVb4JVcYnRvTmm96bY7LNAP8YVtZO6dWEfSTCN9Eirr0hMKkO51/9edDbXCHRq7oPkGTlj+uAVpDS5EW9KBHwodYe9YhaqFXXhsvM4sgvYVuUEhx7E7VecG4beb32l6By7M0svb2j6P3xK9SqtGQykx8d95wxH8xL6AgNHY4FpCeY6oQApdWmbb+qhnNVB1oxFmZzekLGIkcp27X0HWcQdFvnWvr5EBo9CNDS82iO36BoMphi7bi5DOU0O9Nzckm0o1Ot8It2q0kzMrKN2mUtoEZAFIp40UVusCkcPtMQZGEzoW70fDHkKBdrn9hl9ZKI/B4cOGf/0uAdw3oNHF2j4S14Ihk6yg67G8+Ekir6hKKmDxJM+yBqvQ8nhku6yCDV7bXwyXcGUrpbdpl3oaIfAsPr+Tt7/ZU+4fQ12eFTB6DYfZ0SdlC4RgmINMu1fKwsHqpq9AGk1NnlvF4XShh5+JFPQ0y2nKDKpicVVlsqE4LMMphSZd5ktTVY83M6gzA+g5+4HtxU9XiAQLg39b2YZHQAhRK2/AD/hB2PzEoeTm4DXg6HOMQaZyMHhytQ==";

	@Autowired
	JdbcTemplate jdbcTemplate;

	/**
	 * Create initial test data table
	 */
	public void createDatabase() throws Exception {
		logger.info("Creating table");
		jdbcTemplate.execute("DROP TABLE securenote IF EXISTS");
		jdbcTemplate.execute("CREATE TABLE securenote(id SERIAL, title VARCHAR(128), note VARCHAR(4096))");

		logger.info("Inserting data");
		jdbcTemplate.execute("INSERT INTO securenote(title, note) VALUES ('" + TITLE1 + "', '" + NOTE1 + "')");
		jdbcTemplate.execute("INSERT INTO securenote(title, note) VALUES ('" + TITLE2 + "', '" + NOTE2 + "')");
		jdbcTemplate.execute("INSERT INTO securenote(title, note) VALUES ('" + TITLE3 + "', '" + NOTE3 + "')");
	}
}
